export const LOGIN_WITH_PHONE_ACTION_TYPES = {
    LOGIN_WITH_PHONE_REQUEST: "LOGIN_WITH_PHONE_REQUEST",
    LOGIN_WITH_PHONE_FULFILLED: "LOGIN_WITH_PHONE_FULFILLED",
    LOGIN_WITH_PHONE_REJECTED: "LOGIN_WITH_PHONE_REJECTED"
};

export const VERIFY_USER_ACTION_TYPES = {
    VERIFY_USER_REQUEST: "VERIFY_USER_REQUEST",
    VERIFY_USER_FULFILLED: "VERIFY_USER_FULFILLED",
    VERIFY_USER_REJECTED: "VERIFY_USER_REJECTED"
};

export const FORGOT_PASSWORD_ACTION_TYPES = {
    FORGOT_PASSWORD_REQUEST: "FORGOT_PASSWORD_REQUEST",
    FORGOT_PASSWORD_FULFILLED: "FORGOT_PASSWORD_FULFILLED",
    FORGOT_PASSWORD_REJECTED: "FORGOT_PASSWORD_REJECTED"
};

export const CREATE_ACCOUNT_ACTION_TYPES = {
    CREATE_ACCOUNT_REQUEST: "CREATE_ACCOUNT_REQUEST",
    CREATE_ACCOUNT_FULFILLED: "CREATE_ACCOUNT_FULFILLED",
    CREATE_ACCOUNT_REJECTED: "CREATE_ACCOUNT_REJECTED"
};

export const CHECK_ACCOUNT_ACTION_TYPES = {
    CHECK_ACCOUNT_REQUEST: "CHECK_ACCOUNT_REQUEST",
    CHECK_ACCOUNT_FULFILLED: "CHECK_ACCOUNT_FULFILLED",
    CHECK_ACCOUNT_REJECTED: "CHECK_ACCOUNT_REJECTED"
};

export const ADD_EMAIL_ACTION_TYPES = {
    ADD_EMAIL_REQUEST: "ADD_EMAIL_REQUEST",
    ADD_EMAIL_FULFILLED: "ADD_EMAIL_FULFILLED",
    ADD_EMAIL_REJECTED: "ADD_EMAIL_REJECTED"
};