export const LOGIN_WITH_PHONE_ACTION_TYPES = {
    LOGIN_WITH_PHONE_REQUEST: "LOGIN_WITH_PHONE_REQUEST",
    LOGIN_WITH_PHONE_FULFILLED: "LOGIN_WITH_PHONE_FULFILLED",
    LOGIN_WITH_PHONE_REJECTED: "LOGIN_WITH_PHONE_REJECTED"
};

export const VERIFY_USER_ACTION_TYPES = {
    VERIFY_USER_REQUEST: "VERIFY_USER_REQUEST",
    VERIFY_USER_FULFILLED: "VERIFY_USER_FULFILLED",
    VERIFY_USER_REJECTED: "VERIFY_USER_REJECTED"
};

export const FORGOT_PASSWORD_ACTION_TYPES = {
    FORGOT_PASSWORD_REQUEST: "FORGOT_PASSWORD_REQUEST",
    FORGOT_PASSWORD_FULFILLED: "FORGOT_PASSWORD_FULFILLED",
    FORGOT_PASSWORD_REJECTED: "FORGOT_PASSWORD_REJECTED"
};

export const CREATE_ACCOUNT_ACTION_TYPES = {
    CREATE_ACCOUNT_REQUEST: "CREATE_ACCOUNT_REQUEST",
    CREATE_ACCOUNT_FULFILLED: "CREATE_ACCOUNT_FULFILLED",
    CREATE_ACCOUNT_REJECTED: "CREATE_ACCOUNT_REJECTED"
};

export const CHECK_ACCOUNT_ACTION_TYPES = {
    CHECK_ACCOUNT_REQUEST: "CHECK_ACCOUNT_REQUEST",
    CHECK_ACCOUNT_FULFILLED: "CHECK_ACCOUNT_FULFILLED",
    CHECK_ACCOUNT_REJECTED: "CHECK_ACCOUNT_REJECTED"
};

export const ADD_EMAIL_ACTION_TYPES = {
    ADD_EMAIL_REQUEST: "ADD_EMAIL_REQUEST",
    ADD_EMAIL_FULFILLED: "ADD_EMAIL_FULFILLED",
    ADD_EMAIL_REJECTED: "ADD_EMAIL_REJECTED"
};

export const ADD_ADDRESS_ACTION_TYPES = {
    ADD_ADDRESS_REQUEST: "ADD_ADDRESS_REQUEST",
    ADD_ADDRESS_FULFILLED: "ADD_ADDRESS_FULFILLED",
    ADD_ADDRESS_REJECTED: "ADD_ADDRESS_REJECTED"
};

export const GET_USER_WALLET_ACTION_TYPES = {
    GET_USER_WALLET_REQUEST: "GET_USER_WALLET_REQUEST",
    GET_USER_WALLET_FULFILLED: "GET_USER_WALLET_FULFILLED",
    GET_USER_WALLET_REJECTED: "GET_USER_WALLET_REJECTED"
};

export const CREDIT_TRANSACTION_ACTION_TYPES = {
    CREDIT_TRANSACTION_REQUEST: "CREDIT_TRANSACTION_REQUEST",
    CREDIT_TRANSACTION_FULFILLED: "CREDIT_TRANSACTION_FULFILLED",
    CREDIT_TRANSACTION_REJECTED: "CREDIT_TRANSACTION_REJECTED"
};

export const GET_TRANSACTION_ACTION_TYPES = {
    GET_TRANSACTION_REQUEST: "GET_TRANSACTION_REQUEST",
    GET_TRANSACTION_FULFILLED: "GET_TRANSACTION_FULFILLED",
    GET_TRANSACTION_REJECTED: "GET_TRANSACTION_REJECTED"
};

export const GET_FEW_TRANSACTION_ACTION_TYPES = {
    GET_FEW_TRANSACTION_REQUEST: "GET_FEW_TRANSACTION_REQUEST",
    GET_FEW_TRANSACTION_FULFILLED: "GET_FEW_TRANSACTION_FULFILLED",
    GET_FEW_TRANSACTION_REJECTED: "GET_FEW_TRANSACTION_REJECTED"
};

export const REGISTER_A_TASK_ACTION_TYPES = {
    REGISTER_A_TASK_REQUEST: "REGISTER_A_TASK_REQUEST",
    REGISTER_A_TASK_FULFILLED: "REGISTER_A_TASK_FULFILLED",
    REGISTER_A_TASK_REJECTED: "REGISTER_A_TASK_REJECTED"
};